{
  "uid" : "d02f4ae51a2d420c",
  "name" : "test_add[1-2-4-用例描述1]",
  "fullName" : "testCase.caseOne.test_calc.TestCalc#test_add",
  "historyId" : "7980ed253c002b90c1cf3f5698237c45",
  "time" : {
    "start" : 1567597552182,
    "stop" : 1567597553283,
    "duration" : 1101
  },
  "description" : "执行加法测试用例",
  "descriptionHtml" : "<p>执行加法测试用例</p>\n",
  "status" : "failed",
  "statusMessage" : "AssertionError: assert 3 == 4",
  "statusTrace" : "self = <caseOne.test_calc.TestCalc object at 0x0000014D56A7B940>, a = 1, b = 2\nc = 4, d = '用例描述1', foo = 4\n\n    @allure.story(\"测试一个加法运算\")\n    @pytest.mark.parametrize('a,b,c,d',[(1,2,4,\"用例描述1\"),(2,4,6,\"用例描述2\"),(3,7,10,\"用例描述3\")])\n    def test_add(self,a,b,c,d,foo):\n        '''执行加法测试用例'''\n        print(u''+d)\n        # print(\"执行之前调用一次%d\"%foo)\n        sleep(1.1)\n        result = calculate.add(a,b)\n        # print(\"执行期间有调用一次%d\"%foo)\n>       assert result == c\nE       assert 3 == 4\n\ntestCase\\caseOne\\test_calc.py:34: AssertionError",
  "flaky" : false,
  "beforeStages" : [ {
    "name" : "foo",
    "time" : {
      "start" : 1567597552181,
      "stop" : 1567597552181,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "执行加法测试用例",
    "status" : "failed",
    "statusMessage" : "AssertionError: assert 3 == 4",
    "statusTrace" : "self = <caseOne.test_calc.TestCalc object at 0x0000014D56A7B940>, a = 1, b = 2\nc = 4, d = '用例描述1', foo = 4\n\n    @allure.story(\"测试一个加法运算\")\n    @pytest.mark.parametrize('a,b,c,d',[(1,2,4,\"用例描述1\"),(2,4,6,\"用例描述2\"),(3,7,10,\"用例描述3\")])\n    def test_add(self,a,b,c,d,foo):\n        '''执行加法测试用例'''\n        print(u''+d)\n        # print(\"执行之前调用一次%d\"%foo)\n        sleep(1.1)\n        result = calculate.add(a,b)\n        # print(\"执行期间有调用一次%d\"%foo)\n>       assert result == c\nE       assert 3 == 4\n\ntestCase\\caseOne\\test_calc.py:34: AssertionError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "6b3098b0f62dc4c9",
      "name" : "stdout",
      "source" : "6b3098b0f62dc4c9.txt",
      "type" : "text/plain",
      "size" : 14
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "使用pytst+allure的demo-->算数运算"
  }, {
    "name" : "story",
    "value" : "测试一个加法运算"
  }, {
    "name" : "parentSuite",
    "value" : "testCase.caseOne"
  }, {
    "name" : "suite",
    "value" : "test_calc"
  }, {
    "name" : "subSuite",
    "value" : "TestCalc"
  }, {
    "name" : "host",
    "value" : "DESKTOP-PI4KT4H"
  }, {
    "name" : "thread",
    "value" : "13488-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testCase.caseOne.test_calc"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "a",
    "value" : "1"
  }, {
    "name" : "b",
    "value" : "2"
  }, {
    "name" : "c",
    "value" : "4"
  }, {
    "name" : "d",
    "value" : "'用例描述1'"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "d02f4ae51a2d420c.json",
  "parameterValues" : [ "1", "2", "4", "'用例描述1'" ]
}