{"name": "test_post_def[2-data1-错误的账号密码]", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('init', <FixtureRequest for <Function test_post_def[2-data1-\\u9519\\u8bef\\u7684\\u8d26\\u53f7\\u5bc6\\u7801]>>)", "trace": "file D:\\PycharmProjects\\autoApitest-Allure\\testCase\\caseOne\\test_calc.py, line 39\n      @pytest.mark.parametrize('flag,data,des',[(1,{\"userName\":\"admin\",\"passWord\":\"123456\"},\"正确的账号密码\"),(2,{\"userName\":\"admin\",\"passWord\":\"12345\"},\"错误的账号密码\")])\n      def test_post_def(self,flag,data,des,init):\nE       fixture 'init' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, foo, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\PycharmProjects\\autoApitest-Allure\\testCase\\caseOne\\test_calc.py:39"}, "parameters": [{"name": "flag", "value": "2"}, {"name": "data", "value": "{'userName': 'admin', 'passWord': '12345'}"}, {"name": "des", "value": "'错误的账号密码'"}], "start": 1567594286577, "stop": 1567594286577, "uuid": "7c763adf-2d14-402d-9bc3-c771997736b0", "historyId": "419e1cfc1b6c6e86fc107b331d53fc82", "testCaseId": "86ad614be7e8a6709180227cbd53172a", "fullName": "testCase.caseOne.test_calc.TestCalc#test_post_def", "labels": [{"name": "parentSuite", "value": "testCase.caseOne"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-PI4KT4H"}, {"name": "thread", "value": "15856-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCase.caseOne.test_calc"}]}